#import "SearchParameters.h"

#define CX                  @"cx"
#define API_KEY             @"key"
#define QUERY               @"q"
#define SEARCH_TYPE         @"searchType"
#define IMAGE_SIZE          @"imgSize"
#define RESPONSE_TYPE       @"alt"
#define TOTAL_RESULTS       @"totalResults"
#define START_INDEX         @"start"
#define FILE_TYPE           @"fileType"